services:
  redirectgenerator:
    build: .
    user: ${PUID:-0}:${PGID:-0}

    volumes:
      - type: bind
        source: "${WORKING_DIR:?}"
        target: /workdir
        read_only: false
        bind: {}

    environment:
      HOST_TO_REDIRECT_TO: "${HOST_TO_REDIRECT_TO:?}"
      TRAEFIK_SERVICE_NAME: "${TRAEFIK_SERVICE_NAME:-traefik}"
